[parent]
group = 'io.ast.polyglot-maven'
artifact = 'root'
version = '0.0'

[project]
model-version = '4.0.0'
artifact = 'polyglot-maven-toml-test'
packaging = 'jar'
name = 'test Maven polyglot for TOML'
developer = ["ast", { id = "ast2" }, "ast2 <email@com>"]


[properties]
maven.compiler.source = '23'
maven.compiler.target = '23'
project.build.sourceEncoding = 'UTF-8'
junit.version = '5.11.3'

[[dependency]]
group = 'org.slf4j'
artifact = 'slf4j-api'
version = '2.0.16'

[[runtime.dependency]]
group = 'org.slf4j'
artifact = 'slf4j-simple'
version = '2.0.16'

[[test.dependency]]
group = 'org.junit.jupiter'
artifact = 'junit-jupiter-api'
version = '${junit.version}'

[[test.dependency]]
group = 'org.junit.jupiter'
artifact = 'junit-jupiter-engine'
version = '${junit.version}'

[[build.plugin]]
group = 'org.codehaus.mojo'
artifact = 'exec-maven-plugin'
version = '3.3.0'
configuration = { executable = 'maven', main-class = 'io.ast.maven.polyglot.toml.test.Main' }

