[project]
model-version = '4.0.0'
group = 'io.ast.polyglot-maven'
artifact = 'example-kotlin'
version = '0.0'
packaging = 'jar'
name = 'test Maven polyglot for kotlin project'

[property]
maven.compiler.source = "23"
maven.compiler.target = "23"
project.build.sourceEncoding = 'UTF-8'
kotlin.version = '2.0.21'
kotlin.compiler.incremental = true

[dependencies.compile]
"org.jetbrains.kotlin:kotlin-stdlib" = '${kotlin.version}'

[directories]
source = '${project.basedir}/src/main/kotlin'
test-source = '${project.basedir}/src/test/kotlin'

[build.plugin."org.jetbrains.kotlin:kotlin-maven-plugin"]
version = '${kotlin.version}'
executions = [
    {id = 'compile', goal = 'compile'},
    {id = 'test-compile', goal = 'test-compile'}
]

[build.plugin."org.apache.maven.plugins:maven-jar-plugin:3.4.2"]
configuration.archive.manifest = {add-classpath = true, main-class = 'io.ast.maven.polyglot.toml.example_kotlin.MainKt'}

[build.plugin."org.codehaus.mojo:exec-maven-plugin:3.3.0"]
configuration = { executable = 'maven', main-class = 'io.ast.maven.polyglot.toml.example_kotlin.MainKt' }