[parent]
group = 'io.ast.polyglot-maven'
artifact = 'root'
version = '0.0'

[project]
model-version = '4.0.0'
artifact = 'example-java-exec'
packaging = 'jar'
name = 'test Maven polyglot for TOML'


[properties]
maven.compiler.source = '23'
maven.compiler.target = '23'
project.build.sourceEncoding = 'UTF-8'
junit.version = '5.11.3'

[[dependency]]
group = 'org.slf4j'
artifact = 'slf4j-api'
version = '2.0.16'

[dependencies]
runtime = [
    "org.slf4j:slf4j-simple:2.0.16"
]

[dependencies.test]
"org.junit.jupiter:junit-jupiter-api" = "${junit.version}"
"org.junit.jupiter:junit-jupiter-engine" = "${junit.version}"

[build.plugin."org.codehaus.mojo:exec-maven-plugin:3.3.0"]
configuration = { executable = 'maven', main-class = 'io.ast.maven.polyglot.toml.example_java_exec.Main' }

